<a href="https://colab.research.google.com/github/osipov/edu/blob/master/tf0/Solution_Tensorflow_Tensors.ipynb" target="_blank"><img src="https://colab.research.google.com/assets/colab-badge.svg"/></a>

## Import the __`tensorflow`__ package

In [1]:
import tensorflow as tf
tf.random.set_seed(0);

## Create a vector of ten zeros

In [2]:
v = tf.zeros(10)
v

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [3]:
v = tf.Variable(tf.zeros(10))
v[4].assign(1)
v

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)>

## Create a vector with values ranging from 10 to 49

In [41]:
v = tf.range(10, 50)
v

<tf.Tensor: shape=(40,), dtype=int32, numpy=
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49], dtype=int32)>

## Reverse the previous vector

In [42]:
v[::-1]

<tf.Tensor: shape=(40,), dtype=int32, numpy=
array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10], dtype=int32)>

## Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
m = tf.reshape(tf.range(0, 9),(3, 3))
m

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

## Find the indices of the non-zero elements of the following array:

In [7]:
v = tf.constant([1, 2, 0, 0, 4, 0]) # Given
v

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 0, 0, 4, 0], dtype=int32)>

In [8]:
tf.where(v!=0)

<tf.Tensor: shape=(3, 1), dtype=int64, numpy=
array([[0],
       [1],
       [4]])>

In [9]:
v[v!=0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

In [10]:
# same, but preserves shape
tf.gather(v, indices=tf.where(v!=0))

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [4]], dtype=int32)>

## Create a 5x5 identity matrix

In [11]:
m = tf.eye(5)
m

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

## Create a 3x3x3 array with random values

In [12]:
a = tf.random.uniform((3, 3, 3))
a

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.29197514, 0.20656645, 0.53539073],
        [0.5612575 , 0.4166745 , 0.80782795],
        [0.4932251 , 0.99812925, 0.69673514]],

       [[0.1253736 , 0.7098167 , 0.6624156 ],
        [0.57225657, 0.36475348, 0.42051828],
        [0.630057  , 0.913813  , 0.6616472 ]],

       [[0.83347356, 0.08395803, 0.2797594 ],
        [0.0155232 , 0.72637355, 0.7655387 ],
        [0.6798667 , 0.53272796, 0.7565141 ]]], dtype=float32)>

## Find the minimum and maximum values generated in the previous step

In [13]:
tf.math.reduce_min(a).numpy(), tf.math.reduce_max(a).numpy()

(0.015523195, 0.99812925)

## Create a vector with 30 random values and find its mean

In [14]:
v = tf.random.uniform((30,))
tf.math.reduce_mean(v).numpy()

0.5544378

## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [15]:
a = tf.Variable(tf.ones((5, 5)))
a[1:-1, 1:-1].assign(tf.fill(dims=(3,3), value=0.))
a

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

## Try to predict the output of each of the following cells before running them

In [16]:
0 * float('nan')

nan

In [17]:
float('nan') == float('nan')

False

In [18]:
float('inf') > float('nan')

False

In [19]:
float('nan') - float('nan')

nan

In [20]:
0.3 == 3 * 0.1

False

In [21]:
tf.constant([0]) // tf.constant([0]) #crashes the kernel :) continue with the next cell

InvalidArgumentError: ignored

In [22]:
import tensorflow as tf #this is in case you crashed on the previous cell
tf.constant([0.0]) // tf.constant([0.0])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([nan], dtype=float32)>

In [23]:
nan_scalar = tf.constant([float('nan')])

tf.math.is_nan(nan_scalar)

<tf.Tensor: shape=(1,), dtype=bool, numpy=array([ True])>

In [24]:
tf.constant([0.0]) / tf.constant([0.0])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([nan], dtype=float32)>

## Find the integer part of the following array using four different methods:

In [25]:
a = tf.random.normal((10,), dtype = tf.float32)
a

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.8041286 , -0.11153453, -0.84555113,  0.8489615 ,  0.12237629,
        1.3350475 ,  0.619644  , -0.5498301 , -0.6082269 ,  0.8465021 ],
      dtype=float32)>

In [26]:
tf.cast(a, dtype=tf.int8)

<tf.Tensor: shape=(10,), dtype=int8, numpy=array([-1,  0,  0,  0,  0,  1,  0,  0,  0,  0], dtype=int8)>

In [27]:
tf.math.floor(a)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([-2., -1., -1.,  0.,  0.,  1.,  0., -1., -1.,  0.], dtype=float32)>

In [28]:
tf.math.ceil(a) - 1

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([-2., -1., -1.,  0.,  0.,  1.,  0., -1., -1.,  0.], dtype=float32)>

In [29]:
a-tf.truncatemod(a, tf.constant(1.))

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([-1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.], dtype=float32)>

## Create a vector of 10 values from 0 to 1, both included

In [30]:
v = tf.linspace(0, 1, 10)
v

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [31]:
v = tf.linspace(0, 1, 12)[1:-1]
v

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])>

## Subtract the mean of each row of the following matrix

In [32]:
m = tf.random.uniform((3, 3))
m

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.17513537, 0.3179742 , 0.8555474 ],
       [0.41725898, 0.23591995, 0.22561431],
       [0.59902835, 0.8288827 , 0.59770846]], dtype=float32)>

In [33]:
m[0, :]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.17513537, 0.3179742 , 0.8555474 ], dtype=float32)>

In [34]:
[tf.math.reduce_mean(m[i,:]) for i in tf.range(0, 3)]

[<tf.Tensor: shape=(), dtype=float32, numpy=0.44955233>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.29293108>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.6752065>]

In [35]:
tf.math.reduce_mean(m, 1, keepdims = False), 

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.44955233, 0.29293108, 0.6752065 ], dtype=float32)>,)

In [36]:
rowmeans = tf.math.reduce_mean(m, 1, keepdims = True)
rowmeans

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.44955233],
       [0.29293108],
       [0.6752065 ]], dtype=float32)>

In [37]:
# subtract each row mean from every item in row
m - rowmeans

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.27441695, -0.13157812,  0.4059951 ],
       [ 0.1243279 , -0.05701113, -0.06731677],
       [-0.07617813,  0.15367621, -0.07749802]], dtype=float32)>

## Add 1,000,000 numbers together using __`tensorflow`__ vectorized operations

In [38]:
v = tf.random.uniform((1_000_000,))
%timeit tf.math.reduce_sum(v)

The slowest run took 91.56 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 32.3 µs per loop


## Create a 4x4 array of the first 16 powers of 3

In [39]:
a = tf.reshape(tf.range(0, 16), (4, 4))
3 ** a

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]], dtype=int32)>

Copyright 2021 CounterFactual.AI LLC. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.